GET http://localhost:5000/

### create a student
POST http://localhost:5000/api/auth/student/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "student@gmail.com",
    "password": "11223344"
}



### create a teacher
POST http://localhost:5000/api/auth/teacher/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "teacher@gmail.com",
    "password": "11223344"
}
###login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "teacher@gmail.com",
    "password": "11223344"
}

### Get Self
GET http://localhost:5000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWViNzIyM2EyMDZjZjc2MGIwOWUzOWIiLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE3MDk5Mjk5MzR9.OJkwedEZl9CSGk6joDsYiDilQ0_MJYicWYsSDoHjGmc



### Get all students
GET http://localhost:5000/api/students/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWViNzIyM2EyMDZjZjc2MGIwOWUzOWIiLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6InRlYWNoZXJAZ21haWwuY29tIiwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE3MDk5Mjk5MzR9.OJkwedEZl9CSGk6joDsYiDilQ0_MJYicWYsSDoHjGmc
